### ISSUE TITLE
rdatatype works with CNAME but should reply with "No answer"

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#11]
Hi again,
when querying a CNAME record with the default of "rdatatype: A", dnsping resolves the type A record of the CNAME. To my mind it should respond with "No answer", as it does when querying a TXT record.

**Example 1: Querying a txt record with default says "No answer". Correct.**
weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -c 2 -v text.weberdns.de
dnsping.py DNS: 8.8.8.8:53, hostname: text.weberdns.de, rdatatype: A
No answer
No answer

--- 8.8.8.8 dnsping statistics ---
2 requests transmitted, 0 responses received, 100% lost
min=0.000 ms, avg=0.000 ms, max=0.000 ms, stddev=0.000 ms

**Example 2: Querying a txt record with -t txt:**
weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -c 2 -t txt -v text.weberdns.de
dnsping.py DNS: 8.8.8.8:53, hostname: text.weberdns.de, rdatatype: txt
47 bytes from 8.8.8.8: seq=0   time=22.620 ms
text.weberdns.de. 3285 IN TXT "This is a text."
47 bytes from 8.8.8.8: seq=1   time=15.897 ms
text.weberdns.de. 3285 IN TXT "This is a text."

--- 8.8.8.8 dnsping statistics ---
2 requests transmitted, 2 responses received,   0% lost
min=15.897 ms, avg=19.258 ms, max=22.620 ms, stddev=4.754 ms

**Example 3: Querying a CNAME with default works (but should answer with "No answer", or?)**
weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -c 2 -v ip.weberdns.de
dnsping.py DNS: 8.8.8.8:53, hostname: ip.weberdns.de, rdatatype: A
43 bytes from 8.8.8.8: seq=0   time=23.115 ms
ip.webernetz.net. 21262 IN A 80.154.108.235
43 bytes from 8.8.8.8: seq=1   time=15.729 ms
ip.webernetz.net. 21409 IN A 80.154.108.235

--- 8.8.8.8 dnsping statistics ---
2 requests transmitted, 2 responses received,   0% lost
min=15.729 ms, avg=19.422 ms, max=23.115 ms, stddev=5.223 ms

**Comment by farrokhi** [comment]
This is actually happening due to nature of CNAME. So the resolver tries to recursively resolve to get the final answer. This is also the default behavior of "host" and "dig". Let me see to find a logical solution for this.

**Comment by farrokhi** [comment]
I believe this is the expected behavior of DNS query. And "no answer" in this particular scenario is not expected.
