### ISSUE TITLE
payload 8192 is a bug

### ISSUE THREAD

**Issue by notrobpike** [farrokhi/dnsdiag#111]
https://github.com/farrokhi/dnsdiag/blob/master/util/dns.py#L108

The default for the underlying dns.message is 1232. That is the default *for a reason*. Setting it to other than default is a bug. I advise simply remove this setting, however if you must have it then use 1232 as default and let the user explicitly choose a different value. Thanks for your kind attention.

cc @thomasmerz

**Comment by farrokhi** [comment]
Thanks for your bug report
