### ISSUE TITLE
dnseval: -f file not working with fqdns

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#12]
Hi. The "-f file" works only with IP addresses, not with FQDNs. Would be nice.

**weberjoh@jw-nb12:~/dnsdiag$ cat my-server-fqdn.txt**
ns1.weberdns.de
ns2.weberdns.de

**weberjoh@jw-nb12:~/dnsdiag$ ./dnseval.py -f my-server-fqdn.txt pa.weberdns.de**
server              avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)

error: Text input is malformed.

(Have you just renamed dnsutils into dnsdiag? I am a bit confused...)

**Comment by farrokhi** [comment]
This will be fixed in next commit. And yes, I changed the name to avoid confusion with many existing dnstools sites and projects.

**Comment by webernetz** [comment]
Works. Thanks a lot!
