### ISSUE TITLE
DNS Flags aa and ad

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#13]
Hi Babak,

could you add the reporting of some DNS flags into dnsping and dnseval? I am intereseted in the aa (Authoritative Answer from the NS) and ad (Authentic Data for DNSSEC) flag. It would be great to see them either in "dnsping -v", and in dnseval in two additional columns. This could verify whether the authoritative nameserver is amongst the tested ones, and which one of the nameserver is able to validate DNSSEC.

Thanks,
Johannes

**Comment by webernetz** [comment]
Hi Babak,

thanks for that. ;) The flags are almost working, but not the AD flag. Neither in dnsping nor in dnseval.

Request to Google, which validates DNSSEC, ad flag is present:
**weberjoh@jw-nb12:~/dnsdiag$ dig @8.8.8.8 fg.weberdns.de**

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> @8.8.8.8 fg.weberdns.de
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20361
**;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1**

;; ANSWER SECTION:
fg.weberdns.de.         3599    IN      A       80.154.108.233

;; Query time: 46 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon May 16 10:21:35 CEST 2016
;; MSG SIZE  rcvd: 59

But not with dnsping:
**weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -v -c 1 -s 8.8.8.8 fg.weberdns.de**
dnsping.py DNS: 8.8.8.8:53, hostname: fg.weberdns.de, rdatatype: A
40 bytes from 8.8.8.8: seq=0   time=45.544 ms
fg.weberdns.de. 3599 IN A 80.154.108.233
**flags: QR RD RA**

--- 8.8.8.8 dnsping statistics ---
1 requests transmitted, 1 responses received,   0% lost
min=45.544 ms, avg=45.544 ms, max=45.544 ms, stddev=0.000 ms

Nor with dnseval:
**weberjoh@jw-nb12:~/dnsdiag$ ./dnseval.py -f public-servers.txt fg.weberdns.de**
server                   avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  flags
------------------------------------------------------------------------------------------
8.8.8.8                  15.704      14.850      17.986      0.907       %0       QR RD RA
8.8.4.4                  16.267      15.251      18.593      0.922       %0       QR RD RA
2001:4860:4860::8888     16.666      13.081      24.475      4.497       %0       QR RD RA
2001:4860:4860::8844     13.464      12.867      15.099      0.715       %0       QR RD RA
ns1.weberdns.de          2.720       1.836       8.358       2.089       %0    QR AA RD RA
ns2.weberdns.de          6.651       6.046       7.650       0.502       %0       QR AA RD

**Comment by farrokhi** [comment]
Seems like time for another dnspython hack! I will update this ticket.

**Comment by webernetz** [comment]
Hi Babak,

maybe this has something to do with the EDNS OPT extension? I have captured both previous shown DNS queries (dig @8.8.8.8 and ./dnsping -s 8.8.8.8, see above) with Wireshark. This shows that the query from dig has the OPT set, while it is not set from dnsping.
![2016-05-25 10_21_36-dnsping-test-ad-flag pcap](https://cloud.githubusercontent.com/assets/13365684/15533079/2c842eea-2263-11e6-839f-22b058d80cef.png)

**Comment by farrokhi** [comment]
It seems the `AA` flag is show correctly:
```
% ./dnseval.py -f henet-dns.txt -c1 farrokhi.net
server             avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)    flags
--------------------------------------------------------------------------------------------------
216.218.130.2      447.790     447.790     447.790     0.000       %0         QR AA -- RD -- -- --
216.218.131.2      603.192     603.192     603.192     0.000       %0         QR AA -- RD -- -- --
216.218.132.2      790.820     790.820     790.820     0.000       %0         QR AA -- RD -- -- --
216.66.1.2         302.822     302.822     302.822     0.000       %0         QR AA -- RD -- -- --
216.66.80.18       299.945     299.945     299.945     0.000       %0         QR AA -- RD -- -- --
80.154.108.230     0.000       0.000       0.000       0.000       %100       -- -- -- -- -- -- --
213.61.29.182      0.000       0.000       0.000       0.000       %100       -- -- -- -- -- -- --
```
I could also verify that your query does not return `AD` flag:
```
% host -v fg.weberdns.de 213.61.29.182
Trying "fg.weberdns.de"
Using domain server:
Name: 213.61.29.182
Address: 213.61.29.182#53
Aliases: 

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40981
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 4

;; QUESTION SECTION:
;fg.weberdns.de.			IN	A

;; ANSWER SECTION:
fg.weberdns.de.		3600	IN	A	80.154.108.233
...
...
```
Would you check again?

**Comment by webernetz** [comment]
Hi Babak,

at first, thanks for the great update with the fixed flag columns!!!
The `AA` flag is working, but still not the `AD` flag. (You are correct, that my server is not returning the `AD` flag, but that's correct, because it is the authoritative DNS server for weberdns.de. The authoritative server MUST NOT return the AD flag for itself. Please try "host -v fg.weberdns.de 8.8.8.8" and you will see the AD flag.)

Have you had a look at my Wireshark screenshot? To my mind the DNS query from dnseval et al. will not trigger DNSSEC validation...

**Comment by webernetz** [comment]
Yeah! Works.
<code>
weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers-list fg.weberdns.de
server                       avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)    flags
────────────────────────────────────────────────────────────────────────────────────────────────────────────
194.25.0.68                  9.861       3.685       20.535      6.579       %0         QR -- -- RD RA -- --
194.25.0.60                  21.651      8.032       40.500      10.919      %0         QR -- -- RD RA -- --
8.8.8.8                      36.957      16.487      146.569     39.708      %0         QR -- -- RD RA AD --
8.8.4.4                      17.211      16.608      18.496      0.557       %0         QR -- -- RD RA AD --
192.168.110.1                2.331       1.847       3.106       0.468       %0         QR -- -- -- -- -- --
2003:51:6012:110::1          3.403       2.523       6.227       1.069       %0         QR -- -- -- -- -- --
int-dns-v4.webernetz.net     2.791       2.571       2.976       0.154       %0         QR -- -- RD RA AD --
int-dns-v6.webernetz.net     2.906       2.685       3.198       0.188       %0         QR -- -- RD RA AD --
192.168.7.1                  6.066       5.430       7.253       0.518       %0         QR -- -- RD RA -- --
192.168.7.5                  14.348      12.654      22.287      2.870       %0         QR -- -- RD RA AD --
ns1-v4.weberdns.de           6.419       5.791       7.042       0.395       %0         QR AA -- RD -- -- --
ns1-v6.weberdns.de           4.220       3.768       5.260       0.607       %0         QR AA -- RD -- -- --
ns2.weberdns.de              12.710      9.746       24.126      4.436       %0         QR AA -- RD -- -- --
ns3.weberdns.de              26.747      25.982      28.264      0.739       %0         QR AA -- RD -- -- --
</code>
