### ISSUE TITLE
clarify changes required to dnspython library

### ISSUE THREAD

**Issue by anarcat** [farrokhi/dnsdiag#17]
Hi!

I am looking at packaging this for Debian and since the DNSpython library is already packaged in Debian, it is unclear how I will need to proceed.

What exactly are the changes required? Looking at the submodule, i see the following three commits:

* https://github.com/farrokhi/dnspython/commit/35791e1de04b91e59c234691b53d8e533f9f0ace
* https://github.com/farrokhi/dnspython/commit/4838bae1b75e3a33f3723f1f09eacbaaccd51640
* https://github.com/farrokhi/dnspython/commit/bc7445dcd5fe3917f96cac07c7b1f2f645699204

... but those seem to be based on the upstream `python3` branch, which doesn't seem to be merged with a release upstream.

Is that accurate?

Would it be possible to make a pull request that would regularize the situation? :)

Thanks!

**Comment by farrokhi** [comment]
I created a pull request and awaiting for the merge.

**Comment by farrokhi** [comment]
Author was not interested to accept the pull request: https://github.com/rthalley/dnspython/pull/163

**Comment by anarcat** [comment]
i think i was able to somewhat change his mind - but now it requires more changes to dnsdiag, i think. is that something for which i should open a feature request or something?

thanks for following up!

**Comment by farrokhi** [comment]
I will make the changes based on the same ticket.

**Comment by anarcat** [comment]
Awesome, thanks!

**Comment by farrokhi** [comment]
@anarcat updated on dev branch. I am waiting for dnspython maintainer to upload new package to pypi so that I can merge with master.

**Comment by ana-cc** [comment]
Hi, I currently have the ITP bug for dnsdiag in Debian- just waiting for this to be resolved before I proceed.

**Comment by farrokhi** [comment]
I am waiting for dnspython maintainer to upload latest version to pypi. I queried them and haven't receive a response yet.

**Comment by farrokhi** [comment]
@anarcat dnspython people updated their package on pypi with all the changes we needed. So I removed the local modified version of dnspython and now we depend on official dnspython from pypi. I pushed the changes and I believe you can package it for debian now.

**Comment by anarcat** [comment]
@farrokhi awesome, thanks! turns out that @ana-cc has taken over my "RFP" (Request For Package) and turned it into an "ITP" (Intend To Package) which is great news: someone else than me will take care of this. :)

The ITP is here, if anyone wants to follow that progress, and I will notify that issue that this is fixed.
