### ISSUE TITLE
dnseval flags on static vertical columns

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#18]
Hi Babak,

thanks again for adding the flags fo dnseval. But I have one question: Could the flags be on static columns? Currently, it is not easy for the human eye to distinguish between the different flags since they are not on the same column. See below:

![2016-05-25 10_30_34-weberjoh jw-nb12_ _dnsdiag](https://cloud.githubusercontent.com/assets/13365684/15533227/f8c7944c-2263-11e6-98b5-4b0ea67f1b6b.png)

It would be great to have the flags on separate columns. In that way it would be easy to see which server has the QR or AA or whatever flag, or not.

**Comment by webernetz** [comment]
Hi Babak,

it is not working up to now. Is it already live?

**Comment by farrokhi** [comment]
It is on the dev branch. I am merging with HEAD as soon as new dnspython is on pypi. If you need to test it now, you need to use https://github.com/rthalley/dnspython/ HEAD

**Comment by webernetz** [comment]
THANKS!! It's working now.

`weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers-list fg.weberdns.de
server                       avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)    flags
------------------------------------------------------------------------------------------------------------
194.25.0.68                  12.419      8.537       25.341      5.987       %0         QR -- -- RD RA -- --
194.25.0.60                  23.564      21.327      33.443      3.537       %0         QR -- -- RD RA -- --
8.8.8.8                      25.511      15.703      89.692      23.218      %0         QR -- -- RD RA -- --
8.8.4.4                      18.016      15.519      30.744      4.496       %0         QR -- -- RD RA -- --
192.168.110.1                2.492       2.060       2.977       0.343       %0         QR -- -- -- -- -- --
2003:51:6012:110::1          2.488       2.188       2.715       0.181       %0         QR -- -- -- -- -- --
int-dns-v4.webernetz.net     2.232       2.060       2.521       0.158       %0         QR -- -- RD RA -- --
int-dns-v6.webernetz.net     2.207       2.131       2.479       0.108       %0         QR -- -- RD RA -- --
192.168.7.1                  16.027      15.207      18.619      1.100       %0         QR -- -- RD RA -- --
192.168.7.5                  0.000       0.000       0.000       0.000       %100       -- -- -- -- -- -- --
ns1-v4.weberdns.de           2.670       2.096       4.100       0.653       %0         QR AA -- RD -- -- --
ns1-v6.weberdns.de           1.501       1.216       1.909       0.278       %0         QR AA -- RD -- -- --
ns2.weberdns.de              5.273       4.532       6.844       0.660       %0         QR AA -- RD -- -- --
ns3.weberdns.de              48.956      19.507      75.972      18.411      %0         QR AA -- RD -- -- --
`
