### ISSUE TITLE
Maximum wait time for a reply (default: 5) <- default to 2?

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#24]
Just wanted to know what your experiences are with the default timeout of 5 s? From my point of view, this is really long per default. When troubleshooting with dnseval and several DNS servers, it takes multiple minutes until the run is complete. Maybe a default timeout of 2 seconds would fit, since most issues are either "working or not working" than "working but with latency greater 2 seconds".

**Comment by farrokhi** [comment]
Did you try "-w" option? Did it work for you?

**Comment by webernetz** [comment]
Yes it did work. However, I was just wondering about the default 5 long seconds. ;)
