### ISSUE TITLE
dnseval: option for displaying DNS answer?

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#28]
Hi Babak,
could you add an option to display the DNS reply from each server? I am currently investigating some caching issues. While it is really great that I can already see the TTL, it would be even better to see the reply with its A/AAAA/TXT/WHATEVER record. (Similar to the -v option within dnsping.)
;) Thanks!!!

**Comment by farrokhi** [comment]
Doable. I need to figure out a way to do not spam the console and show it in a clean way.

**Comment by webernetz** [comment]
Yes, absolutely correct. (Since I am using 24" displays, the console is wide enough *g*.)

**Comment by webernetz** [comment]
Yeah, Babak, thanks for that. Works perfect:
<pre><code>weberjoh@jw-nb15-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers -v fg.weberdns.de
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl        flags
------------------------------------------------------------------------------------------------------------------
194.25.0.68               4.759       4.296       6.493       0.658       %0       3587       QR -- -- RD RA -- --
Answer 1 [ fg.weberdns.de. 3587 IN A 80.154.108.233 ]

194.25.0.60               8.666       8.394       9.037       0.186       %0       3586       QR -- -- RD RA -- --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]

2003:40:2000::53          4.338       4.151       4.528       0.130       %0       3586       QR -- -- RD RA -- --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]

2003:56::53               9.129       8.285       13.347      1.599       %0       3586       QR -- -- RD RA -- --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]

8.8.8.8                   22.418      13.754      61.837      14.479      %0       3586       QR -- -- RD RA AD --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]
Answer 2 [ fg.weberdns.de. 3586 IN RRSIG A 8 3 3600 20170511164905 20170411161257 61119 weberdns.de. itnqWmuts+3vWtKZ20/Ix50cxFzmx7pL Kq+IBP4P8s2TpBvPvzzApCQybCUVycgB rQQepiWLWujAozo4NMcPN29b8xhTnp06 MeSWtxR+wd8966Nl5dLvvJPc9Fy4OSsI TnwhhnPNjgZDc1ubLLJW0gOW9dKZnqHk 88Fnwg1JZQc= ]

8.8.4.4                   27.237      14.648      69.757      19.530      %0       3586       QR -- -- RD RA AD --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]
Answer 2 [ fg.weberdns.de. 3586 IN RRSIG A 8 3 3600 20170511164905 20170411161257 61119 weberdns.de. itnqWmuts+3vWtKZ20/Ix50cxFzmx7pL Kq+IBP4P8s2TpBvPvzzApCQybCUVycgB rQQepiWLWujAozo4NMcPN29b8xhTnp06 MeSWtxR+wd8966Nl5dLvvJPc9Fy4OSsI TnwhhnPNjgZDc1ubLLJW0gOW9dKZnqHk 88Fnwg1JZQc= ]

2001:4860:4860::8888      18.355      15.179      23.218      3.205       %0       3586       QR -- -- RD RA AD --
Answer 1 [ fg.weberdns.de. 3586 IN A 80.154.108.233 ]
Answer 2 [ fg.weberdns.de. 3586 IN RRSIG A 8 3 3600 20170511164905 20170411161257 61119 weberdns.de. itnqWmuts+3vWtKZ20/Ix50cxFzmx7pL Kq+IBP4P8s2TpBvPvzzApCQybCUVycgB rQQepiWLWujAozo4NMcPN29b8xhTnp06 MeSWtxR+wd8966Nl5dLvvJPc9Fy4OSsI TnwhhnPNjgZDc1ubLLJW0gOW9dKZnqHk 88Fnwg1JZQc= ]

2001:4860:4860::8844      18.319      14.534      25.676      3.643       %0       3598       QR -- -- RD RA AD --
Answer 1 [ fg.weberdns.de. 3598 IN A 80.154.108.233 ]
Answer 2 [ fg.weberdns.de. 3598 IN RRSIG A 8 3 3600 20170511164905 20170411161257 61119 weberdns.de. itnqWmuts+3vWtKZ20/Ix50cxFzmx7pL Kq+IBP4P8s2TpBvPvzzApCQybCUVycgB rQQepiWLWujAozo4NMcPN29b8xhTnp06 MeSWtxR+wd8966Nl5dLvvJPc9Fy4OSsI TnwhhnPNjgZDc1ubLLJW0gOW9dKZnqHk 88Fnwg1JZQc= ]
</code></pre>
