### ISSUE TITLE
dnstraceroute: Expert hint with private DNS server

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#30]
Hi Babak,
just saw this one:

<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ sudo ./dnstraceroute.py -x google.de
dnstraceroute.py DNS: 192.168.120.22:53, hostname: google.de, rdatatype: A
1       pa-dmz.webernetz.net (192.168.110.1) 1 ms
2       int-dns.webernetz.net (192.168.120.22) 8 ms

=== Expert Hints ===
 [*] public DNS server is next to a private IP address (possible hijacking)
</code></pre>

Since I have internal DNS servers, it is no problem that it is next to a private IP. ;)

**Comment by farrokhi** [comment]
Well, that is correct. I should change the behavior so that if this happens within a few hops, it would be ignored. but if it happens after 5-6 hops, then that would be suspicious.
