### ISSUE TITLE
Traceback since new version?

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#32]
Hi Babak,

I just installed the current version. I am not able to use any of the tools. Any idea?
<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnsping.py
Traceback (most recent call last):
  File "./dnsping.py", line 37, in <module>
    import dns.flags
ImportError: No module named 'dns'
weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnseval.py
Traceback (most recent call last):
  File "./dnseval.py", line 38, in <module>
    import dns.rdatatype
ImportError: No module named 'dns'
weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnstraceroute.py
Traceback (most recent call last):
  File "./dnstraceroute.py", line 38, in <module>
    import dns.query
ImportError: No module named 'dns'
</code></pre>

**Comment by farrokhi** [comment]
Please try this:
```
pip install -r requirements.txt
```

**Comment by webernetz** [comment]
Still not working:
<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ pip install -r requirements.txt
Collecting dnspython==1.15.0 (from -r requirements.txt (line 1))
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 1.9MB/s
Installing collected packages: dnspython
Successfully installed dnspython-1.14.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
weberjoh@jw-nb12-lx:~/dnsdiag$ ./dnsping.py
Traceback (most recent call last):
  File "./dnsping.py", line 37, in <module>
    import dns.flags
ImportError: No module named 'dns'
</code></pre>

**Comment by farrokhi** [comment]
if you have a symbolic link named `dns` in your `dnsdiag` directory, please remove it. It is an artifact from the time that we had a modified version of dnspython,

**Comment by webernetz** [comment]
Hm, I have not symbolic link:
<pre><code>weberjoh@jw-nb12-lx:~/dnsdiag$ ls -ahl
total 104K
drwxrwxr-x  4 weberjoh weberjoh 4.0K Nov 15 15:52 .
drwxr-xr-x 27 weberjoh weberjoh 4.0K Nov 15 15:52 ..
drwxrwxr-x  4 weberjoh weberjoh 4.0K Nov 15 15:53 cymruwhois
-rwxrwxr-x  1 weberjoh weberjoh 8.7K Nov 15 15:52 dnseval.py
-rwxrwxr-x  1 weberjoh weberjoh 8.3K Nov 15 15:52 dnsping.py
-rwxrwxr-x  1 weberjoh weberjoh  13K Nov 15 15:52 dnstraceroute.py
drwxrwxr-x  9 weberjoh weberjoh 4.0K Nov 15 15:53 .git
-rw-rw-r--  1 weberjoh weberjoh  783 Nov 15 15:52 .gitignore
-rw-rw-r--  1 weberjoh weberjoh  104 Nov 15 15:52 .gitmodules
-rw-rw-r--  1 weberjoh weberjoh 1.3K Nov 15 15:52 LICENSE
-rw-rw-r--  1 weberjoh weberjoh   77 Nov 15 15:52 MANIFEST.in
-rw-rw-r--  1 weberjoh weberjoh  149 Nov 15 15:52 public-servers.txt
-rw-rw-r--  1 weberjoh weberjoh 6.2K Nov 15 15:52 README.md
-rw-rw-r--  1 weberjoh weberjoh   18 Nov 15 15:52 requirements.txt
-rw-rw-r--  1 weberjoh weberjoh  247 Nov 15 15:52 rootservers.txt
-rw-rw-r--  1 weberjoh weberjoh 1.3K Nov 15 15:52 setup.py
-rw-rw-r--  1 weberjoh weberjoh   60 Nov 15 15:52 TODO.md
-rw-rw-r--  1 weberjoh weberjoh  217 Nov 15 15:52 .travis.yml
</code></pre>

**Comment by farrokhi** [comment]
Let me see if I can reproduce this and will update the issue. 

-- 
Babak Farrokhi

**Comment by farrokhi** [comment]
I could not reproduce it here. Do you have multiple versions of python installed? If so, you need to make sure `dnspython` module is installed for `python3`. I am not sure if `pip` command on your platform represents python 2 or 3. On my platform I need to run `pip3` to install python3 modules. 
Could you please check that?

**Comment by webernetz** [comment]
Hi Babak,

oh thanks for the hint. Now its working with:
<pre><code>pip3 install -r requirements.txt</code></pre>

I still don't know why this problems occured since it worked perfectly during the lasts month. Anyway, thank you!
