### ISSUE TITLE
dnseval -m: 100 % loss and no Output in ms

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#48]
Hi again,

currently dnseval is not reporting anything. It only lists 100 % loss and no timings at all. Please note that I can see in tcpdump that the "NXDomain" replies are coming from the DNS servers.

<pre><code>weberjoh@nb15-lx:~/dnsdiag$ ./dnseval.py -f ../dns-server2 -m heise.de
server                   avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl        flags
-----------------------------------------------------------------------------------------------------------------
8.8.8.8                  0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2001:4860:4860::8888     0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
9.9.9.9                  0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2620:fe::fe              0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --</code></pre>

**Comment by farrokhi** [comment]
I believe this is related to #47 , therefore closing this so that we can followup on the other ticket.
