### ISSUE TITLE
dnseval.py error on execution

### ISSUE THREAD

**Issue by iancnorden** [farrokhi/dnsdiag#50]
dnsdiag:% ./dnseval.py -t AAAA -f public-v4.txt -c10 yahoo.com
Traceback (most recent call last):
  File "./dnseval.py", line 287, in main
    with open(inputfilename, 'rt') as flist:
FileNotFoundError: [Errno 2] No such file or directory: 'public-v4.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dnseval.py", line 367, in <module>
    main()
  File "./dnseval.py", line 362, in main
    print('%s: %s' % (server, e))
UnboundLocalError: local variable 'server' referenced before assignment

===

Fix: 
Define server before the try: on line 280.

===

Happy to throw a PR from my fork, let me know.

**Comment by farrokhi** [comment]
Thank you for your contribution!
