### ISSUE TITLE
dnsping: pinging SERVFAIL or NXDOMAIN intentionally

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#60]
Hi Babak,

we are currently testing several DNS appliances. Beside pinging for correct FQDNs we are also testing non-existent queries as well as DNSSEC failures (to check whether the DNS server correctly validates DNSSEC). However, both cases are currently not possible with dnsping as it exits with an error code rather than start pinging:

<pre><code>weberjoh@nb15-lx:~/dnsdiag$ ./dnsping.py sigfail.verteiltesysteme.net
dnsping.py DNS: 2003:de:2016:120::a08:53:53, hostname: sigfail.verteiltesysteme.net, rdatatype: A
No response to dns request
weberjoh@nb15-lx:~/dnsdiag$
weberjoh@nb15-lx:~/dnsdiag$ ./dnsping.py thisdomaindosnotexist.net
dnsping.py DNS: 2003:de:2016:120::a08:53:53, hostname: thisdomaindosnotexist.net, rdatatype: A
Hostname does not exist
</code></pre>

Could you please process these DNS queries as well?

And could you add another column in the output that displays the "status" of each request, such as: NOERROR, NXDOMAIN, SERVFAIL? (Not only in the -v output, but by default, since it does not increase the output size dramatically.)

Thanks a lot!! ;)
Johannes

**Comment by farrokhi** [comment]
Seems like I cannot resolve `sigfail.verteiltesysteme.net` at all. Is this expected?

**Comment by webernetz** [comment]
Yep, probably because you're using a DNSSEC validating DNS resolver. ;) Hence you should see a "SERVFAIL" rather than "NXDOMAIN". You can use the `+cd` option with `dig` to "check disable" the DNSSEC validation:

<pre><code>weberjoh@nb17-lx2:~$ dig sigfail.verteiltesysteme.net @8.8.8.8 +cd

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> sigfail.verteiltesysteme.net @8.8.8.8 +cd
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31067
;; flags: qr rd ra cd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;sigfail.verteiltesysteme.net.  IN      A

;; ANSWER SECTION:
sigfail.verteiltesysteme.net. 59 IN     A       134.91.78.139

;; Query time: 15 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jan 12 15:50:17 UTC 2021
;; MSG SIZE  rcvd: 73
</code></pre>

--> That's why it would be great to have a default output that states whether the status is "NOERROR", "NXDOMAIN" (in case the domain does not exist") or "SERVFAIL" (which indicates a DNSSEC failure among others). Thanks a lot!

**Comment by farrokhi** [comment]
This should be solved (along with a bunch of nice additions) in this branch: https://github.com/farrokhi/dnsdiag/tree/eliminate-stub-resolver

Would you please test and feedback, if you feel adventurous?

**Comment by farrokhi** [comment]
Fixed in version 2.0.0 d6aab02d8301ee9c0ec97d9997932061befb903e

**Comment by webernetz** [comment]
Yup. Nice. (Though a bit unhandy since it requires --verbose to show the actual output, which in turn displays that many lines. To my mind it would be great if "--flags" would also display the rcode of NOERROR, NXDOMAIN, or SERVFAIL, which would still fit into a single line per request.)

Anyway, thanks for coding this feature!!

**Comment by webernetz** [comment]
Yes, this test for example is irritating: I am querying a DNSSEC failure, but it looks like everything is ok, though I used the --flags and --dnssec options:
<pre><code>weberjoh@nb17-lx2:~/dnsdiag$ ./dnsping.py --count 4 --server 9.9.9.9 --flags --dnssec sigfail.verteiltesysteme.net
dnsping.py DNS: 9.9.9.9:53, hostname: sigfail.verteiltesysteme.net, proto: UDP, rdatatype: A, flags: RD
57 bytes from 9.9.9.9: seq=1   time=27.007 ms [QR RD RA]
57 bytes from 9.9.9.9: seq=2   time=9.562 ms [QR RD RA]
57 bytes from 9.9.9.9: seq=3   time=88.500 ms [QR RD RA]
57 bytes from 9.9.9.9: seq=4   time=9.688 ms [QR RD RA]

--- 9.9.9.9 dnsping statistics ---
4 requests transmitted, 4 responses received, 0% lost
min=9.562 ms, avg=33.689 ms, max=88.500 ms, stddev=37.448 ms
</code></pre>

If it would display the "SERVFAIL" with every line it would be clear that something is wrong. ;)

**Comment by farrokhi** [comment]
like this?

```
% ./dnsping.py --count 4 --server 9.9.9.9 --flags --dnssec sigfail.verteiltesysteme.net
dnsping.py DNS: 9.9.9.9:53, hostname: sigfail.verteiltesysteme.net, proto: UDP, rdatatype: A, flags: RD
57 bytes from 9.9.9.9: seq=1   time=155.755 ms [QR RD RA]  SERVFAIL
57 bytes from 9.9.9.9: seq=2   time=19.483 ms [QR RD RA]  SERVFAIL
57 bytes from 9.9.9.9: seq=3   time=92.750 ms [QR RD RA]  SERVFAIL
57 bytes from 9.9.9.9: seq=4   time=19.544 ms [QR RD RA]  SERVFAIL

--- 9.9.9.9 dnsping statistics ---
4 requests transmitted, 4 responses received, 0% lost
min=19.483 ms, avg=71.883 ms, max=155.755 ms, stddev=65.714 ms
```

and this?

```
% ./dnsping.py --count 4 --server 9.9.9.9 --flags --dnssec nonexistent.verteiltesysteme.net
dnsping.py DNS: 9.9.9.9:53, hostname: nonexistent.verteiltesysteme.net, proto: UDP, rdatatype: A, flags: RD
774 bytes from 9.9.9.9: seq=1   time=46.067 ms [QR RD RA AD]  NXDOMAIN
774 bytes from 9.9.9.9: seq=2   time=41.132 ms [QR RD RA AD]  NXDOMAIN
774 bytes from 9.9.9.9: seq=3   time=17.647 ms [QR RD RA AD]  NXDOMAIN
774 bytes from 9.9.9.9: seq=4   time=42.732 ms [QR RD RA AD]  NXDOMAIN

--- 9.9.9.9 dnsping statistics ---
4 requests transmitted, 4 responses received, 0% lost
min=17.647 ms, avg=36.895 ms, max=46.067 ms, stddev=12.995 ms
```

I guess this solves the problem. Because the DNS server actually responds and the response is measureable. However the response code might not be desirable (NXDOMAIN, SERVFAIL, etc).

**Comment by farrokhi** [comment]
fixed ba9102b541423c59edcf90bedce34ba6d0957c2d

**Comment by webernetz** [comment]
YES YES YES, that's exactly what I was looking for. Thanks a lot! ;)

**Comment by farrokhi** [comment]
This would be in v2.0.2, but for the meantime you can simple clone the master branch.

**Comment by webernetz** [comment]
Yes, I already did:
<pre><code>weberjoh@nb17-lx2:~/dnsdiag$ ./dnsping.py --server 1.1.1.1 --flags sigfail.verteiltesysteme.net
dnsping.py DNS: 1.1.1.1:53, hostname: sigfail.verteiltesysteme.net, proto: UDP, rdatatype: A, flags: RD
63 bytes from 1.1.1.1: seq=1   time=17.784 ms [QR RD RA]  SERVFAIL
63 bytes from 1.1.1.1: seq=2   time=10.056 ms [QR RD RA]  SERVFAIL
63 bytes from 1.1.1.1: seq=3   time=10.292 ms [QR RD RA]  SERVFAIL
63 bytes from 1.1.1.1: seq=4   time=10.425 ms [QR RD RA]  SERVFAIL
^C
--- 1.1.1.1 dnsping statistics ---
4 requests transmitted, 4 responses received, 0% lost
min=10.056 ms, avg=12.139 ms, max=17.784 ms, stddev=3.766 ms
</code></pre>
