### ISSUE TITLE
dnseval: column with status

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#61]
Hi again,
related to my feature request for dnsping (https://github.com/farrokhi/dnsdiag/issues/60), querying non-existent domains or DNSSEC failures is not working with dnseval either, since the output states all zeros instead of the milliseconds and so on. Furthermore, another column for the "status" of the reponse code such as NOERROR, NXDOMAIN or SERVFAIL would be great. This would immediately reveal the problems (if any) of the servers:

<pre><code>weberjoh@nb15-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers sigfail.verteiltesysteme.net
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl        flags
------------------------------------------------------------------------------------------------------------------
194.25.0.68               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
194.25.0.60               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2003:40:2000::53          0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2003:56::53               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
8.8.8.8                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
8.8.4.4                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2001:4860:4860::8888      0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2001:4860:4860::8844      0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
9.9.9.9                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2620:fe::fe               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
resolver1.opendns.com     15.777      9.936       18.189      2.794       %0       60         QR -- -- RD RA -- --
resolver2.opendns.com     12.475      10.231      18.033      3.407       %0       60         QR -- -- RD RA -- --
weberjoh@nb15-lx:~/dnsdiag$ ./dnseval.py -f ../dns-servers thisdomaindoesnotexist.net
server                    avg(ms)     min(ms)     max(ms)     stddev(ms)  lost(%)  ttl        flags
------------------------------------------------------------------------------------------------------------------
194.25.0.68               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
194.25.0.60               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2003:40:2000::53          0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2003:56::53               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
8.8.8.8                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
8.8.4.4                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2001:4860:4860::8888      0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2001:4860:4860::8844      0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
9.9.9.9                   0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
2620:fe::fe               0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
resolver1.opendns.com     0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
resolver2.opendns.com     0.000       0.000       0.000       0.000       %100     N/A        -- -- -- -- -- -- --
</code></pre>

Just in case you have some spare time. ;)

Johannes

**Comment by farrokhi** [comment]
Fixed in d6aab02d8301ee9c0ec97d9997932061befb903e
