### ISSUE TITLE
Should --json have gone to standard out with different option for file?

### ISSUE THREAD

**Issue by freemansoft** [farrokhi/dnsdiag#74]
I'd like to consume dnsdiag as a library call from another ISP connection monitoring program.  It seems like the --json should have changed the output format and a --outfile or some other option should have written to file.  I'm guessing the idea behind using `json` was to make it machine parseable. In that case it should have been output in a way easier to consume.

**Comment by farrokhi** [comment]
When `--json` is given, it saves a json copy of the results in `results.json`. However I am changing this behavior so that `--json` would require a file name, and `--json -` to send output to stdout.
And also I should omit the normal output and only output json.

**Comment by farrokhi** [comment]
I also refactored the code and move some redundant code to `util.dns`. You can now use `util.dns.ping()` library function instead of invoking `dnseval`.
