### ISSUE TITLE
dnsping error

### ISSUE THREAD

**Issue by p1r473** [farrokhi/dnsdiag#82]
```
./dnsping.py google.ca
dnsping.py DNS: 192.168.1.1:53, hostname: google.ca, proto: UDP, rdatatype: A, flags: RD
Traceback (most recent call last):
  File "./dnsping.py", line 291, in <module>
    main()
  File "./dnsping.py", line 216, in main
    src_ip, src_port, ignore_unexpected=True)
  File "/usr/local/lib/python3.5/dist-packages/dns/query.py", line 321, in udp
    s.bind(source)
TypeError: string or unicode text buffer expected, not int
```

**Comment by farrokhi** [comment]
you are probably using an older version of python (<3.6). I just retagged the repo and rerolled the packages with a fix for backward compatibility. It should be solved in efd6f2eda607d86ce737c5857197077a922d38df.

**Comment by p1r473** [comment]
Thanks, yes, my Tinkerboard doesnt support 3.6
Thank you.

**Comment by webernetz** [comment]
Yep, same here on a Ubuntu 16.04.7 LTS machine (on which I used dnsdiag for the last years...)
<pre><code>weberjoh@nb15-lx:~/dnsdiag$ ./dnsping.py --server 1.1.1.1 --flags heise.de
Traceback (most recent call last):
  File "./dnsping.py", line 39, in <module>
    import dns.flags
  File "/home/weberjoh/.local/lib/python3.5/site-packages/dns/flags.py", line 24, in <module>
    class Flag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
</code></pre>

**Comment by p1r473** [comment]
Thanks, fixed now.

**Comment by farrokhi** [comment]
> Yep, same here on a Ubuntu 16.04.7 LTS machine (on which I used dnsdiag for the last years...)
> 
> ```
> weberjoh@nb15-lx:~/dnsdiag$ ./dnsping.py --server 1.1.1.1 --flags heise.de
> Traceback (most recent call last):
>   File "./dnsping.py", line 39, in 
>     import dns.flags
>   File "/home/weberjoh/.local/lib/python3.5/site-packages/dns/flags.py", line 24, in 
>     class Flag(enum.IntFlag):
> AttributeError: module 'enum' has no attribute 'IntFlag'
> ```

Verified in Ubuntu 16.04.7 with python 3.5.2 and dnspython 2.1.0.
This one seems to be a dnspython library itself:
```
root@6092af5195a8:/dnsdiag# python3
Python 3.5.2 (default, Jan 26 2021, 13:30:48)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dns.flags
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/dns/flags.py", line 24, in <module>
    class Flag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```
