### ISSUE TITLE
-4/-6 switch for forcing IPv4/IPv6

### ISSUE THREAD

**Issue by webernetz** [farrokhi/dnsdiag#9]
At first: great tool. Many thanks!

Do you have the possibility to add a -4/-6 switch for forcing IPv4 or IPv6 for the connection? E.g., I am using the following command:
./dnsping.py -s ns1.weberdns.de ip.weberdns.de
but want to test it either with IPv4 or with IPv6. Currently, it defaults to IPv6 (which is good). I know that I can simply put the IPv4 address of the DNS server in the "-s 1.2.3.4" section, but I would like to have a well-known -4 or -6 flag.

Thanks!
Johannes

**Comment by farrokhi** [comment]
please kindly test and feedback

**Comment by webernetz** [comment]
Of course.
1) when using only "-6" you should default to the Google IPv6 Public DNS Server "2001:4860:4860::8888" (and not to 8.8.8.8 which obviously is not working ;))
2) when querying a dual stacked DNS server, the -6 switch works, but not the -4. It is trying to connect to the v6 address:

**weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -s ns1.weberdns.de -6 ip.weberdns.de**
dnsping.py DNS: 2003:51:6012:110::22:53, hostname: ip.weberdns.de, rdatatype: A
43 bytes from 2003:51:6012:110::22: seq=0   time=10.808 ms
43 bytes from 2003:51:6012:110::22: seq=1   time=2.147 ms


--- 2003:51:6012:110::22 dnsping statistics ---
10 requests transmitted, 10 responses received,   0% lost
min=1.618 ms, avg=2.668 ms, max=10.808 ms, stddev=2.865 ms


**weberjoh@jw-nb12:~/dnstools$ ./dnsping.py -s ns1.weberdns.de -4 ip.weberdns.de**
dnsping.py DNS: 2003:51:6012:110::22:53, hostname: ip.weberdns.de, rdatatype: A
^C

**Comment by webernetz** [comment]
Hi Babak. Have you seen my feedback? I am still getting the same error:

**weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -s ns1.weberdns.de -4 ip.weberdns.de**
dnsping.py DNS: 2003:51:6012:110::22:53, hostname: ip.weberdns.de, rdatatype: A
Request timeout
^CTraceback (most recent call last):
  File "./dnsping.py", line 226, in <module>
    main()
  File "./dnsping.py", line 170, in main
    answers = resolver.query(hostname, dnsrecord, source_port=src_port, source=src_ip, tcp=use_tcp, af=af)
  File "/home/weberjoh/dnsdiag/dns/resolver.py", line 956, in query
    time.sleep(sleep_time)
  File "./dnsping.py", line 67, in signal_handler
    if should_stop:  # pressed twice, so exit immediately
UnboundLocalError: local variable 'should_stop' referenced before assignment

(Can I mark this request us unclosed? I don't know.)

**Comment by farrokhi** [comment]
It is not working here:
```
% host ip.weberdns.de ns1.weberdns.de
Using domain server:
Name: ns1.weberdns.de
Address: 80.154.108.230#53
Aliases: 

ip.weberdns.de is an alias for ip.webernetz.net.
Host ip.webernetz.net not found: 5(REFUSED)
Host ip.webernetz.net not found: 5(REFUSED)
```
can you please check?

**Comment by webernetz** [comment]
What do you mean exactly? My problem is, that the -4 option is not working since it is still trying to get the "-s server" via IPv6 and not via IPv4.

(And yes, "ip.weberdns.de" is a bad example because it is a CNAME to ip.webernetz.net, which won't be resolved by ns1.weberdns.de. So please try "host pa.weberdns.de ns1.weberdns.de". This should work.)

**Comment by webernetz** [comment]
Now, without any switch an a FQDN, the following appears:

weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -s google-public-dns-a.google.com heise.de
Traceback (most recent call last):
  File "./dnsping.py", line 145, in main
    ipaddress.ip_address(dnsserver)
  File "/usr/lib/python3.4/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'google-public-dns-a.google.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./dnsping.py", line 226, in <module>
    main()
  File "./dnsping.py", line 148, in main
    dnsserver = socket.getaddrinfo(dnsserver, port=None, family=af)[1][4][0]
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
TypeError: an integer is required (got type NoneType)

**Comment by webernetz** [comment]
Great!! Thanks a lot!

**weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -s google-public-dns-a.google.com heise.de**
dnsping.py DNS: 8.8.8.8:53, hostname: heise.de, rdatatype: A
32 bytes from 8.8.8.8: seq=0   time=19.257 ms
32 bytes from 8.8.8.8: seq=1   time=15.614 ms
32 bytes from 8.8.8.8: seq=2   time=16.285 ms
32 bytes from 8.8.8.8: seq=3   time=15.434 ms
32 bytes from 8.8.8.8: seq=4   time=14.760 ms
32 bytes from 8.8.8.8: seq=5   time=15.408 ms
32 bytes from 8.8.8.8: seq=6   time=14.500 ms
32 bytes from 8.8.8.8: seq=7   time=14.993 ms
32 bytes from 8.8.8.8: seq=8   time=15.339 ms
32 bytes from 8.8.8.8: seq=9   time=15.630 ms

--- 8.8.8.8 dnsping statistics ---
10 requests transmitted, 10 responses received,   0% lost
min=14.500 ms, avg=15.722 ms, max=19.257 ms, stddev=1.338 ms
**weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -s google-public-dns-a.google.com -6 heise.de**
dnsping.py DNS: 2001:4860:4860::8888:53, hostname: heise.de, rdatatype: A
32 bytes from 2001:4860:4860::8888: seq=0   time=16.254 ms
32 bytes from 2001:4860:4860::8888: seq=1   time=11.709 ms
32 bytes from 2001:4860:4860::8888: seq=2   time=13.084 ms
32 bytes from 2001:4860:4860::8888: seq=3   time=12.890 ms
32 bytes from 2001:4860:4860::8888: seq=4   time=11.984 ms
32 bytes from 2001:4860:4860::8888: seq=5   time=13.886 ms
32 bytes from 2001:4860:4860::8888: seq=6   time=13.897 ms
32 bytes from 2001:4860:4860::8888: seq=7   time=11.680 ms
32 bytes from 2001:4860:4860::8888: seq=8   time=12.981 ms
32 bytes from 2001:4860:4860::8888: seq=9   time=12.950 ms

--- 2001:4860:4860::8888 dnsping statistics ---
10 requests transmitted, 10 responses received,   0% lost
min=11.680 ms, avg=13.132 ms, max=16.254 ms, stddev=1.353 ms
**weberjoh@jw-nb12:~/dnsdiag$ ./dnsping.py -s google-public-dns-a.google.com -4 heise.de**
dnsping.py DNS: 8.8.8.8:53, hostname: heise.de, rdatatype: A
32 bytes from 8.8.8.8: seq=0   time=17.124 ms
32 bytes from 8.8.8.8: seq=1   time=15.049 ms
32 bytes from 8.8.8.8: seq=2   time=14.764 ms
32 bytes from 8.8.8.8: seq=3   time=15.321 ms
32 bytes from 8.8.8.8: seq=4   time=15.965 ms
32 bytes from 8.8.8.8: seq=5   time=15.388 ms
32 bytes from 8.8.8.8: seq=6   time=15.576 ms
32 bytes from 8.8.8.8: seq=7   time=16.456 ms
32 bytes from 8.8.8.8: seq=8   time=15.479 ms
32 bytes from 8.8.8.8: seq=9   time=14.997 ms

--- 8.8.8.8 dnsping statistics ---
10 requests transmitted, 10 responses received,   0% lost
min=14.764 ms, avg=15.612 ms, max=17.124 ms, stddev=0.722 ms

**Comment by farrokhi** [comment]
Glad it worked for you! Please feel free to provide me feedback and bug reports, so that I can improve the quality of this toolset.

-- 
Babak Farrokhi

**Comment by webernetz** [comment]
Yes, I will. Really thanks for your patience!
